version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: guess-backend
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: guess-frontend
    restart: always
