name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t sakthi05/guess-game-frontend ./frontend
          docker push sakthi05/guess-game-frontend

      - name: Build and Push Backend Image
        run: |
          docker build -t sakthi05/guess-game-backend ./backend
          docker push sakthi05/guess-game-backend

      - name: Deploy on EC2 (via SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/guess-game
            docker-compose pull
            docker-compose up -d
